Improve bootstrap script to make use of the standard shellscript template

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,40 +1,60 @@
 #!/usr/bin/env sh
 
+set -euo pipefail
+IFS=$'\n\t'
+
+readonly logfile="/tmp/$(basename "$0").log"
+info()    { echo "[INFO]    $*" | tee -a "$logfile" >&2 ; }
+warning() { echo "[WARNING] $*" | tee -a "$logfile" >&2 ; }
+error()   { echo "[ERROR]   $*" | tee -a "$logfile" >&2 ; }
+fatal()   { echo "[FATAL]   $*" | tee -a "$logfile" >&2 ; exit 1 ; }
+
+lockfile="/tmp/yadm-bootstrap.lock"
 resources="$HOME/.config/yadm/bootstrap-resources"
 
-init_submodules() (
-   # Because Git submodule commands cannot operate without a work tree, they must
-   # be run from within $HOME (assuming this is the root of your dotfiles)
-   cd "$HOME"
-   echo "Init submodules"
-   echo yadm submodule update --recursive --init
-)
-
-install_packages() (   
-   echo "Install packages"
-
-   # Manjaro
-   if uname -r | grep -i manjaro >/dev/null 2>&1 ; then
-      manjaro_packages
-   fi
-)
-
-manjaro_packages() {
-   yay -S --needed - < "$resources/packages.manjaro"
+cleanup() {
+  rm -f "$lockfile"
+	exit
 }
 
-install_python_modules() (
-   echo "Install Python modules"
-   pip install --user pywal ipython sympy pandas
+init_submodules() (
+  # Because Git submodule commands cannot operate without a work tree, they must
+  # be run from within $HOME (assuming this is the root of your dotfiles)
+  cd "$HOME"
+  info "Init submodules"
+  echo yadm submodule update --recursive --init
 )
 
-configure_vs_code() (   
-   echo "Configure VS Code"
-   cat "$resources/vscode.extensions" | xargs -n 1 code --force --install-extension
-)
+install_packages() {
+  info "Install packages"
 
-init_submodules
-install_packages
-install_python_modules
-configure_vs_code
-exit 0
+  # Manjaro
+  if uname -r | grep -i manjaro >/dev/null 2>&1 ; then
+      manjaro_packages
+  fi
+}
+
+manjaro_packages() {
+  yay -S --needed - < "$resources/packages.manjaro"
+}
+
+install_python_modules() {
+  info "Install Python modules"
+  pip install --user pywal ipython sympy pandas
+}
+
+configure_vs_code() { 
+  info "Configure VS Code"
+  cat "$resources/vscode.extensions" | xargs -n 1 code --force --install-extension || true
+}
+
+# Main script
+if { set -C; 2>/dev/null >"$lockfile"; }; then
+  trap cleanup EXIT  
+  init_submodules
+  install_packages
+  install_python_modules
+  configure_vs_code
+else
+  fatal "Lock file '"$lockfile"' exists... Exiting"
+fi
